### ISSUE TITLE
关于车牌检测的请教

### ISSUE THREAD

**Issue by pange1802703882** [mcmingchang/yolox_keypoint_segment#7]
你好，请问你在ccpd数据集上使用车牌的四个角点做车牌检测和直接用左上角右下角的坐标做车牌检测，效果有明显的改善吗？
还有我在项目里面没有找到你的车牌关键点检测的model呀，可以提供一下吗，感谢

**Comment by mcmingchang** [comment]
代码是通用的，你可以试试，模型不方便提供
